sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
  matrix:
    - WP_VERSION=latest
    - WP_VERSION=trunk

before_script:
  - composer validate
  - bash bin/install-package-tests.sh

script: ./vendor/bin/behat --strict
